### ISSUE TITLE
Static Path's

### ISSUE THREAD

**Issue by Et3rn4lBlu3** [nikolakosticc/officefusion_1.0#1]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Nikola Kostic\\\\Downloads\\\\digital_assistant_software_1.0-main\\\\templates\\\\main_template.png'

Pogledaj whatsapp :)

**Comment by nikolakosticc** [comment]
Reseno! Hvala ti puno!

In English : 
Error fixed! Thanks!
